### ISSUE TITLE
Improvements or additions to documentation

### ISSUE THREAD

**Issue by emaoumaima** [Perla-dev/testshell00#1]
Testing a shell typically involves verifying that it behaves as expected and handles various commands and inputs correctly. Below, I'll outline some common approaches for testing a shell script, shell program, or command-line interface (CLI).

1. Unit Testing: write unit tests for individual functions or components within your script.
2. Integration Testing: running it with different inputs and verifying the expected outputs.
3. Manual Testing
4. Positive and Negative Testing: with valid and expected inputs to ensure it produces the correct output.
5. Edge Case Testing:such as empty input, large input, or corner cases that may expose vulnerabilities.
6. Security Testing: like input validation, command injection, and handling of special characters.
7. Test Automation: like `Expect`, `bash automated testing system (BATS)`, or custom scripts.
8. Code Coverage Analysis: with tools like `shcov`.

**Comment by Perla-dev** [comment]
Great tips!
